/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunlerIndexRouteImport } from './routes/urunler.index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerIndexRoute = UrunlerIndexRouteImport.update({
  id: '/urunler/',
  path: '/urunler/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler/': typeof UrunlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler': typeof UrunlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler/': typeof UrunlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/urunler/$slug' | '/urunler/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/urunler/$slug' | '/urunler'
  id: '__root__' | '/' | '/urunler/$slug' | '/urunler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UrunlerSlugRoute: typeof UrunlerSlugRoute
  UrunlerIndexRoute: typeof UrunlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/': {
      id: '/urunler/'
      path: '/urunler'
      fullPath: '/urunler/'
      preLoaderRoute: typeof UrunlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UrunlerSlugRoute: UrunlerSlugRoute,
  UrunlerIndexRoute: UrunlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
